[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.3.2"

[context.deploy-preview]
  command = "yarn build-preview"

  [[redirects]]
  from = "https://nepal-guide.netlify.com/*"
  to = "https://www.nepal-guide.ru:splat"
  status = 301!
